### ISSUE TITLE
Choosing License

### ISSUE THREAD

**Issue by smeskos** [fortran-lang/benchmarks#7]
While studying the stopwatch links @ivan-pi posted in #6, it occurred to me that each one was under a different license. While preparing benchmarks we will need to use software written in different languages under different licenses. As I understand, benchmarks will be part of the fortran-lang website therefore under MIT license. 
What happens in the following scenario: I am preparing a Nbody benchmark, I already coded the Fortran version under MIT, I copied the C++ version from rosettacode.org, in order to start comparisons, which is under GFDL (v1.2) (and will do the same for the Julia version) and if I choose to time it with eg. the second link in #6 which is under GPLv3 will there be a conflict/problem? Can I publish the codes and the results and if yes, under what license?

**Comment by certik** [comment]
I would do MIT by default for anything we write ourselves. If we take somebody's else code, then we simply note the license terms in that file.

Regarding GPL, each benchmark is a standalone code, so maybe we can use it for that benchmark. If not, we might need to have an optional separate repository for benchmarks whose license would not allow us to include them.
